project:
  title: "D-penicillamine in Primary Biliary Cholangitis"
  type: default

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-summary: "Show the code"
    fig-cap-location: bottom
    embed-resources: true

execute:
  echo: true
  warning: false
  message: false
